export const APP_ROUTES = {
  SIGN_IN: '/sign-in',
  PROFILE_SETUP: '/profile-setup',
  DASHBOARD: '/dashboard',
  PROJECTS: '/projects',
  PROJECTS_NEW: '/projects/new',
  PROJECT_DETAIL: '/projects/:projectId',
  AGENTS: '/agents',
  AGENTS_NEW: '/agents/new',
  GATEWAYS: '/gateways',
  GATEWAYS_NEW: '/gateways/new',
  GATEWAY_DETAIL: '/gateways/:gatewayId',
  DOCUMENTATION: '/documentation',
  SKILLS: '/skills',
  PROJECT_GROUPS: '/project-groups',
  PROJECT_GROUPS_NEW: '/project-groups/new',
  PROJECT_GROUP_DETAIL: '/project-groups/:groupId',
  CUSTOM_FIELDS: '/custom-fields',
  TAGS: '/tags',
  TAG_ADD: '/tags/add',
  INVITE: '/invite',
  ACTIVITY: '/activity',
  ONBOARDING: '/onboarding'
} as const
