export type OpenClawMethodAccess = 'read' | 'write' | 'admin'

export interface OpenClawMethodDefinition {
  method: string
  group: string
  access: OpenClawMethodAccess
  description: string
  sampleParams?: Record<string, unknown>
}

export const OPENCLAW_PROTOCOL_VERSION = 3
export const OPENCLAW_OPERATOR_SCOPES = ['operator.read', 'operator.admin', 'operator.approvals', 'operator.pairing'] as const
export const OPENCLAW_TEST_MESSAGE = 'How are you?'

export const OPENCLAW_METHODS: OpenClawMethodDefinition[] = [
  { method: 'health', group: 'Core', access: 'read', description: 'Returns lightweight gateway health.' },
  { method: 'diagnostics.stability', group: 'Core', access: 'read', description: 'Returns bounded diagnostic stability metadata.' },
  { method: 'status', group: 'Core', access: 'read', description: 'Returns runtime status, server version, and capability metadata.' },
  { method: 'gateway.identity.get', group: 'Core', access: 'read', description: 'Returns the gateway device identity used by relay and pairing flows.' },
  { method: 'system-presence', group: 'Core', access: 'read', description: 'Returns connected operator and node presence.' },
  { method: 'system-event', group: 'Core', access: 'write', description: 'Appends a system event and can broadcast presence context.' },
  { method: 'last-heartbeat', group: 'Core', access: 'read', description: 'Returns the latest persisted heartbeat event.' },
  { method: 'set-heartbeats', group: 'Core', access: 'write', description: 'Toggles heartbeat processing on the gateway.' },
  { method: 'logs.tail', group: 'Core', access: 'read', description: 'Reads recent gateway logs.', sampleParams: { lines: 100 } },
  { method: 'usage.status', group: 'Usage', access: 'read', description: 'Returns usage tracking status.' },
  { method: 'usage.cost', group: 'Usage', access: 'read', description: 'Returns cost/usage summary.' },
  { method: 'doctor.memory.status', group: 'Usage', access: 'read', description: 'Returns vector-memory and embedding readiness.', sampleParams: { probe: false } },
  { method: 'doctor.memory.remHarness', group: 'Usage', access: 'read', description: 'Returns a bounded read-only REM harness preview.' },
  { method: 'sessions.usage', group: 'Usage', access: 'read', description: 'Returns per-session usage summaries.' },
  { method: 'sessions.usage.timeseries', group: 'Usage', access: 'read', description: 'Returns usage timeseries for one session.' },
  { method: 'sessions.usage.logs', group: 'Usage', access: 'read', description: 'Returns usage log entries for one session.' },
  { method: 'web.login.start', group: 'Channels', access: 'write', description: 'Starts a QR or web login flow.' },
  { method: 'web.login.wait', group: 'Channels', access: 'write', description: 'Waits for a web login flow to complete.' },
  { method: 'push.test', group: 'Channels', access: 'write', description: 'Sends a test push to a registered iOS node.' },
  { method: 'voicewake.get', group: 'Channels', access: 'read', description: 'Reads wake-word triggers.' },
  { method: 'voicewake.set', group: 'Channels', access: 'write', description: 'Updates wake-word triggers.' },
  { method: 'send', group: 'Messaging', access: 'write', description: 'Sends a direct outbound channel message.' },
  { method: 'tts.status', group: 'TTS', access: 'read', description: 'Returns TTS subsystem status.' },
  { method: 'tts.providers', group: 'TTS', access: 'read', description: 'Lists configured TTS providers.' },
  { method: 'tts.enable', group: 'TTS', access: 'write', description: 'Enables TTS.' },
  { method: 'tts.disable', group: 'TTS', access: 'write', description: 'Disables TTS.' },
  { method: 'tts.convert', group: 'TTS', access: 'write', description: 'Converts text to speech.', sampleParams: { text: 'Hello' } },
  { method: 'tts.setProvider', group: 'TTS', access: 'write', description: 'Sets active TTS provider.', sampleParams: { provider: 'default' } },
  { method: 'talk.config', group: 'TTS', access: 'read', description: 'Returns effective Talk config.', sampleParams: { includeSecrets: false } },
  { method: 'talk.speak', group: 'TTS', access: 'write', description: 'Synthesizes speech through the active Talk provider.', sampleParams: { text: 'Hello' } },
  { method: 'secrets.reload', group: 'Config', access: 'admin', description: 'Reloads active SecretRefs.' },
  { method: 'secrets.resolve', group: 'Config', access: 'admin', description: 'Resolves command-target secret assignments.' },
  { method: 'config.get', group: 'Config', access: 'read', description: 'Reads gateway config.' },
  { method: 'config.schema', group: 'Config', access: 'read', description: 'Reads config schema.' },
  { method: 'config.schema.lookup', group: 'Config', access: 'read', description: 'Reads schema metadata for one config path.', sampleParams: { path: 'models.providers' } },
  { method: 'config.set', group: 'Config', access: 'admin', description: 'Replaces a config key/value.', sampleParams: { key: 'path.to.key', value: true } },
  { method: 'config.patch', group: 'Config', access: 'admin', description: 'Patches gateway config.', sampleParams: { patch: {} } },
  { method: 'config.apply', group: 'Config', access: 'admin', description: 'Applies pending config changes.' },
  { method: 'update.run', group: 'Config', access: 'admin', description: 'Runs the gateway update flow.' },
  { method: 'update.status', group: 'Config', access: 'read', description: 'Returns the latest update status.' },
  { method: 'models.list', group: 'Models', access: 'read', description: 'Lists available models/providers.' },
  { method: 'artifacts.list', group: 'Artifacts', access: 'read', description: 'Lists transcript-derived artifacts.', sampleParams: { sessionKey: 'openmissioncontrol:<gatewayId>:test' } },
  { method: 'artifacts.get', group: 'Artifacts', access: 'read', description: 'Returns one transcript-derived artifact.', sampleParams: { sessionKey: 'openmissioncontrol:<gatewayId>:test', artifactId: '<artifactId>' } },
  { method: 'artifacts.download', group: 'Artifacts', access: 'read', description: 'Downloads a transcript-derived artifact.', sampleParams: { sessionKey: 'openmissioncontrol:<gatewayId>:test', artifactId: '<artifactId>' } },
  { method: 'sessions.list', group: 'Sessions', access: 'read', description: 'Lists chat sessions.' },
  { method: 'sessions.subscribe', group: 'Sessions', access: 'read', description: 'Subscribes to session changes.' },
  { method: 'sessions.unsubscribe', group: 'Sessions', access: 'read', description: 'Unsubscribes from session changes.' },
  { method: 'sessions.messages.subscribe', group: 'Sessions', access: 'read', description: 'Subscribes to transcript changes.', sampleParams: { sessionKey: 'openmissioncontrol:<gatewayId>:test' } },
  { method: 'sessions.messages.unsubscribe', group: 'Sessions', access: 'read', description: 'Unsubscribes from transcript changes.', sampleParams: { sessionKey: 'openmissioncontrol:<gatewayId>:test' } },
  { method: 'sessions.preview', group: 'Sessions', access: 'read', description: 'Returns a session preview.', sampleParams: { sessionKey: 'openmissioncontrol:<gatewayId>:test' } },
  { method: 'sessions.resolve', group: 'Sessions', access: 'read', description: 'Resolves or canonicalizes a session target.', sampleParams: { sessionKey: 'openmissioncontrol:<gatewayId>:test' } },
  { method: 'sessions.create', group: 'Sessions', access: 'write', description: 'Creates a session.', sampleParams: { key: 'openmissioncontrol:<gatewayId>:test' } },
  { method: 'sessions.send', group: 'Sessions', access: 'write', description: 'Sends a message into a session.', sampleParams: { sessionKey: 'openmissioncontrol:<gatewayId>:test', message: 'Hello' } },
  { method: 'sessions.steer', group: 'Sessions', access: 'write', description: 'Interrupts and steers an active session.', sampleParams: { sessionKey: 'openmissioncontrol:<gatewayId>:test', message: 'Adjust course' } },
  { method: 'sessions.abort', group: 'Sessions', access: 'write', description: 'Aborts active work for a session.', sampleParams: { sessionKey: 'openmissioncontrol:<gatewayId>:test' } },
  { method: 'sessions.patch', group: 'Sessions', access: 'write', description: 'Creates or updates a session.', sampleParams: { key: 'openmissioncontrol:<gatewayId>:test', label: 'OpenMissionControl Gateway Test' } },
  { method: 'sessions.reset', group: 'Sessions', access: 'write', description: 'Resets a session.', sampleParams: { sessionKey: 'openmissioncontrol:<gatewayId>:test' } },
  { method: 'sessions.delete', group: 'Sessions', access: 'write', description: 'Deletes a session.', sampleParams: { sessionKey: 'openmissioncontrol:<gatewayId>:test' } },
  { method: 'sessions.compact', group: 'Sessions', access: 'write', description: 'Compacts session history.', sampleParams: { sessionKey: 'openmissioncontrol:<gatewayId>:test' } },
  { method: 'sessions.get', group: 'Sessions', access: 'read', description: 'Returns the full stored session row.', sampleParams: { sessionKey: 'openmissioncontrol:<gatewayId>:test' } },
  { method: 'chat.send', group: 'Chat', access: 'write', description: 'Sends a chat message.', sampleParams: { sessionKey: 'openmissioncontrol:<gatewayId>:test', message: 'How are you?', deliver: true } },
  { method: 'chat.history', group: 'Chat', access: 'read', description: 'Reads chat history.', sampleParams: { sessionKey: 'openmissioncontrol:<gatewayId>:test', limit: 50 } },
  { method: 'chat.abort', group: 'Chat', access: 'write', description: 'Aborts active chat generation.', sampleParams: { sessionKey: 'openmissioncontrol:<gatewayId>:test' } },
  { method: 'chat.inject', group: 'Chat', access: 'write', description: 'Injects a message into a session.', sampleParams: { sessionKey: 'openmissioncontrol:<gatewayId>:test', message: 'Note' } },
  { method: 'agents.list', group: 'Agents', access: 'read', description: 'Lists OpenClaw agents.' },
  { method: 'agents.create', group: 'Agents', access: 'write', description: 'Creates an OpenClaw agent.', sampleParams: { name: 'omc-agent-<id>', workspace: 'agents/omc-agent-<id>' } },
  { method: 'agents.update', group: 'Agents', access: 'write', description: 'Updates OpenClaw agent metadata.', sampleParams: { agentId: 'omc-agent-<id>', name: 'Agent name', workspace: 'agents/omc-agent-<id>' } },
  { method: 'agents.delete', group: 'Agents', access: 'write', description: 'Deletes an OpenClaw agent.', sampleParams: { agentId: 'omc-agent-<id>', deleteFiles: true } },
  { method: 'agents.files.list', group: 'Agents', access: 'read', description: 'Lists files for an OpenClaw agent.', sampleParams: { agentId: 'omc-agent-<id>' } },
  { method: 'agents.files.get', group: 'Agents', access: 'read', description: 'Reads a file for an OpenClaw agent.', sampleParams: { agentId: 'omc-agent-<id>', name: 'AGENT.md' } },
  { method: 'agents.files.set', group: 'Agents', access: 'write', description: 'Writes a file for an OpenClaw agent.', sampleParams: { agentId: 'omc-agent-<id>', name: 'AGENT.md', content: '# Agent' } },
  { method: 'agent.identity.get', group: 'Agents', access: 'read', description: 'Returns effective assistant identity.', sampleParams: { sessionKey: 'openmissioncontrol:<gatewayId>:test' } },
  { method: 'agent.wait', group: 'Agents', access: 'read', description: 'Waits for a run to finish.', sampleParams: { runId: '<runId>' } },
  { method: 'node.pair.request', group: 'Pairing', access: 'admin', description: 'Requests node pairing.' },
  { method: 'node.pair.list', group: 'Pairing', access: 'read', description: 'Lists node pairing requests.' },
  { method: 'node.pair.approve', group: 'Pairing', access: 'admin', description: 'Approves node pairing.', sampleParams: { id: '<requestId>' } },
  { method: 'node.pair.reject', group: 'Pairing', access: 'admin', description: 'Rejects node pairing.', sampleParams: { id: '<requestId>' } },
  { method: 'node.pair.remove', group: 'Pairing', access: 'admin', description: 'Removes a paired node.', sampleParams: { id: '<nodeId>' } },
  { method: 'node.pair.verify', group: 'Pairing', access: 'read', description: 'Verifies node pairing.' },
  { method: 'device.pair.list', group: 'Pairing', access: 'read', description: 'Lists device pairing requests.' },
  { method: 'device.pair.approve', group: 'Pairing', access: 'admin', description: 'Approves device pairing.', sampleParams: { deviceId: '<deviceId>' } },
  { method: 'device.pair.reject', group: 'Pairing', access: 'admin', description: 'Rejects device pairing.', sampleParams: { deviceId: '<deviceId>' } },
  { method: 'device.pair.remove', group: 'Pairing', access: 'admin', description: 'Removes a paired device.', sampleParams: { deviceId: '<deviceId>' } },
  { method: 'device.token.rotate', group: 'Pairing', access: 'admin', description: 'Rotates a paired device token.', sampleParams: { deviceId: '<deviceId>', role: 'operator' } },
  { method: 'device.token.revoke', group: 'Pairing', access: 'admin', description: 'Revokes a paired device token.', sampleParams: { deviceId: '<deviceId>', role: 'operator' } },
  { method: 'node.list', group: 'Nodes', access: 'read', description: 'Lists known and connected nodes.' },
  { method: 'node.describe', group: 'Nodes', access: 'read', description: 'Returns node details.', sampleParams: { nodeId: '<nodeId>' } },
  { method: 'node.rename', group: 'Nodes', access: 'write', description: 'Renames a paired node.', sampleParams: { nodeId: '<nodeId>', label: 'Node' } },
  { method: 'node.invoke', group: 'Nodes', access: 'write', description: 'Forwards a command to a connected node.', sampleParams: { nodeId: '<nodeId>', command: 'camera.snap', payload: {} } },
  { method: 'node.invoke.result', group: 'Nodes', access: 'read', description: 'Returns a node invoke result.', sampleParams: { requestId: '<requestId>' } },
  { method: 'node.event', group: 'Nodes', access: 'write', description: 'Carries a node-originated event back into the gateway.' },
  { method: 'node.canvas.capability.refresh', group: 'Nodes', access: 'write', description: 'Refreshes scoped canvas capability tokens.' },
  { method: 'node.pending.pull', group: 'Nodes', access: 'write', description: 'Pulls queued work for a connected node.' },
  { method: 'node.pending.ack', group: 'Nodes', access: 'write', description: 'Acknowledges queued node work.' },
  { method: 'node.pending.enqueue', group: 'Nodes', access: 'write', description: 'Enqueues durable pending work for an offline node.' },
  { method: 'node.pending.drain', group: 'Nodes', access: 'write', description: 'Drains durable pending work for an offline node.' },
  { method: 'exec.approval.get', group: 'Approvals', access: 'read', description: 'Reads one execution approval request.', sampleParams: { id: '<approvalId>' } },
  { method: 'exec.approval.list', group: 'Approvals', access: 'read', description: 'Lists execution approval requests.' },
  { method: 'exec.approvals.get', group: 'Approvals', access: 'read', description: 'Reads execution approval policy.' },
  { method: 'exec.approvals.set', group: 'Approvals', access: 'admin', description: 'Updates execution approval policy.' },
  { method: 'exec.approvals.node.get', group: 'Approvals', access: 'read', description: 'Reads node approval policy.' },
  { method: 'exec.approvals.node.set', group: 'Approvals', access: 'admin', description: 'Updates node approval policy.' },
  { method: 'exec.approval.request', group: 'Approvals', access: 'write', description: 'Creates approval request.' },
  { method: 'exec.approval.waitDecision', group: 'Approvals', access: 'read', description: 'Waits for one approval decision.', sampleParams: { id: '<approvalId>', timeoutMs: 30000 } },
  { method: 'exec.approval.resolve', group: 'Approvals', access: 'admin', description: 'Resolves approval request.' },
  { method: 'plugin.approval.request', group: 'Approvals', access: 'write', description: 'Creates plugin approval request.' },
  { method: 'plugin.approval.list', group: 'Approvals', access: 'read', description: 'Lists plugin approval requests.' },
  { method: 'plugin.approval.waitDecision', group: 'Approvals', access: 'read', description: 'Waits for one plugin approval decision.' },
  { method: 'plugin.approval.resolve', group: 'Approvals', access: 'admin', description: 'Resolves plugin approval request.' },
  { method: 'wizard.start', group: 'Wizard', access: 'write', description: 'Starts OpenClaw wizard.' },
  { method: 'wizard.next', group: 'Wizard', access: 'write', description: 'Advances OpenClaw wizard.' },
  { method: 'wizard.cancel', group: 'Wizard', access: 'write', description: 'Cancels OpenClaw wizard.' },
  { method: 'wizard.status', group: 'Wizard', access: 'read', description: 'Reads OpenClaw wizard status.' },
  { method: 'wake', group: 'Automation', access: 'write', description: 'Schedules an immediate or next-heartbeat wake text injection.', sampleParams: { text: 'Wake' } },
  { method: 'cron.list', group: 'Automation', access: 'read', description: 'Lists scheduled work.' },
  { method: 'cron.status', group: 'Automation', access: 'read', description: 'Reads scheduler status.' },
  { method: 'cron.add', group: 'Automation', access: 'write', description: 'Adds scheduled work.' },
  { method: 'cron.update', group: 'Automation', access: 'write', description: 'Updates scheduled work.' },
  { method: 'cron.remove', group: 'Automation', access: 'write', description: 'Removes scheduled work.' },
  { method: 'cron.run', group: 'Automation', access: 'write', description: 'Runs scheduled work immediately.' },
  { method: 'cron.runs', group: 'Automation', access: 'read', description: 'Lists scheduled work runs.' },
  { method: 'commands.list', group: 'Tools', access: 'read', description: 'Lists available commands.' },
  { method: 'tools.catalog', group: 'Tools', access: 'read', description: 'Returns the tool catalog.' },
  { method: 'tools.effective', group: 'Tools', access: 'read', description: 'Returns effective tools for the active context.' },
  { method: 'tools.invoke', group: 'Tools', access: 'write', description: 'Invokes a tool.', sampleParams: { tool: '<toolName>', input: {} } },
  { method: 'skills.status', group: 'Skills', access: 'read', description: 'Returns skills subsystem status.' },
  { method: 'skills.search', group: 'Skills', access: 'read', description: 'Searches skills.', sampleParams: { query: '' } },
  { method: 'skills.detail', group: 'Skills', access: 'read', description: 'Returns skill details.', sampleParams: { id: '<skillId>' } },
  { method: 'skills.install', group: 'Skills', access: 'write', description: 'Installs a skill.', sampleParams: { id: '<skillId>' } },
  { method: 'skills.update', group: 'Skills', access: 'write', description: 'Updates a skill.', sampleParams: { id: '<skillId>' } },
  { method: 'skills.bins', group: 'Skills', access: 'read', description: 'Lists skill binary metadata.' },
  { method: 'talk.mode', group: 'Channels', access: 'write', description: 'Reads or updates talk mode.' },
  { method: 'channels.status', group: 'Channels', access: 'read', description: 'Reads channel status.' },
  { method: 'channels.logout', group: 'Channels', access: 'admin', description: 'Logs out a channel.' }
]

export function isKnownOpenClawMethod(method: string): boolean {
  return OPENCLAW_METHODS.some((item) => item.method === method)
}

export function openClawMethod(method: string): OpenClawMethodDefinition | undefined {
  return OPENCLAW_METHODS.find((item) => item.method === method)
}
